[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = False
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
warn_unreachable = True
strict_equality = True
pretty = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-composer.*]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-hydra.*]
ignore_missing_imports = True

[mypy-wandb.*]
ignore_missing_imports = True

[mypy-lm_eval.*]
ignore_missing_imports = True

[mypy-einops.*]
ignore_missing_imports = True

[mypy-torchmetrics.*]
ignore_missing_imports = True
